export enum PERMISSION {
  CREATE_POST = 'CREATE_POST',
  READ_POST = 'READ_POST',
  UPDATE_POST = 'UPDATE_POST',
  DELETE_POST = 'DELETE_POST',
}

export const USER_PERSMISSIONS = [PERMISSION.READ_POST];

export const ADMIN_PERSMISSIONS = [
  PERMISSION.READ_POST,
  PERMISSION.DELETE_POST,
];
export const AUTHOR_PERSMISSIONS = [
  PERMISSION.CREATE_POST,
  PERMISSION.READ_POST,
  PERMISSION.UPDATE_POST,
];
